[General]
name=chlo
long_name = Phytoplankton Chlorophyll-a Concentration

[Input]
# Directory to output results
input_dir = /home/users/yumengch/rekec/get_owt/owt_data
# The date and time format follows the 1989 C standard
# for reference see:
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
# Note % has to be escaped with another % in configparser
filename_format = owt_chlo_%%Y%%m.nc
# Specifying data frequency:
# it follows numpy datetime units:
# https://numpy.org/doc/stable/reference/arrays.datetime.html#datetime-units
# e.g., '6h' for every 6 hours, '1D' for daily, '1m' 1 months,
# '1Y' for yearly data.
# or leave it empty for all available netCDF files in the input directory
data_freq = 1M
# the starting date for data using numpy datetime format, e.g., 2010-03-14T15:00:00.00
data_start = 2015-02-01T00:00:00.00
data_end = 2015-03-01T00:00:00.00
# a list of variable names, separated by commas
# these values should include at least two of d_ob, d_ab, d_oa, lon, lat variable names
# it should also include those variables that help us get a mask for binning
variables = d_ob,d_ab,d_oa,lon,lat
d_ob_name = d_ob
d_ab_name = d_ab
d_oa_name = d_oa
lon_name = lon
lat_name = lat
# if specified, the predictor is speficied by this variable name
# unless mask_func is given in the Python function call.
pred_name = mask

[Predictor]
name = OWT
# Number of predictor classes (bins)
n_classes = 14
# Maximum number of observations per day
# this is used to limit the data volume
max_obs_per_day = 10000
# minimum number of samples to compute covariance estimates
n_samples = 100
# window size for smoothing correlations, better if even
smooth_window = 6

[Grid]
# Discrete radial distances for correlations
# maximum correlation distance in km
max_distance = 10000
# Distance interval for correlations in km
distance_interval = 200
