[ObsTypes]
# List of observation types to process, separated by commas
# Each Observation types corresponds to their own configuration files.
# The config files should end with .ini
# When more than one obs type is specified here,
# cross covariance between observations will be computed.
obs_config_files = chlo_all,carbon_all

[Uncertainty]
# One can choose to one or all of the following uncertainty sources to compute
# separated by commas:
# R: only the observation error covariance matrix
# HBH: only the HBH covariance matrix
# R+HBH: the sum of the two covariance matrices
estimate = R,HBH,R+HBH

[Output]
# Directory to output results
output_dir = output
# Filename to output results
# no need to put .nc here, it will be added automatically
binned_filename = binned
cov_filename = cov